### ISSUE TITLE
Bump build number to 1002 to allow gcc7 builds

### ISSUE THREAD

**Issue by isuruf** [conda-forge/gshhg-gmt-feedstock#3]
And remove build number 1 packages.

@ocefpaf, this might be the issue with gmt.

**Comment by ocefpaf** [comment]
We should fix this too but that was not the issue. I had to update the circle token to get it uploaded. These packages are "kind of noarch" and that is why we missed them during the migration.

**Comment by leouieda** [comment]
OK, so anything using the new compilers needs to be >=1000 is that right? I'll open a PR bumping the build number here

**Comment by ocefpaf** [comment]
> OK, so anything using the new compilers needs to be >=1000 is that right? I'll open a PR bumping the build number here

Yep. But because these are not really compiled it does really matter here. We only need to make them available on the `gcc7` channel so `gmt` could use them.
